### ISSUE TITLE
Gyroscope value can not be taken

### ISSUE THREAD

**Issue by ankandas04** [bikeAccidentDetector/BikeApp#1]
Developer doesn't have a cell phone. Due to lock down and **unavailability of a cell phone**, _gyroscope value can not be detected_ .

**Comment by joydey1800** [comment]
Dev here, sorry for the inconvenience.

**Comment by joydey1800** [comment]
Since the required hardware is not available, values are hardcoded as of now. The application is running on the basis of those preset values. - Gyroscope
